export const actionTypes = {
    PLUS: 'PLUS',
    MINUS: 'MINUS',
    CHANGE_TITLE: 'CHANGE_TITLE',
    WAIT: 'WAIT',
    RECEIVE_DATA: 'RECEIVE_DATA',
    RECEIVE_URLS: 'RECEIVE_URLS',
    CHANGE_VIEW_MODE: 'CHANGE_VIEW_MODE'
};